services:
  - type: web
    name: leo-backend
    env: python
    rootDir: .
    buildCommand: "pip install -r requirements.txt && python -m spacy download fr_core_news_sm"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT src.main:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///instance/app.db
    healthCheckPath: /api/health
# rebuild trigger
